#pragma once
#include <unordered_map>
#include <string>

enum class EventCode {
	None,
	onConsoleInput,
	onConsoleOutput,
	onSelectForm,
	onUseItem,
	onPlaceBlock,
	onDestroyBlock,
	onOpenChest,
	onOpenBarrel,
	onCloseChest,
	onCloseBarrel,
	onContainerChange,
	onChangeDimension,
	onMobDie,
	onMobHurt,
	onRespawn,
	onChat,
	onInputText,
	onCommandBlockUpdate,
	onInputCommand,
	onCommandBlockPerform,
	onPlayerJoin,
	onPlayerLeft,
	onPlayerAttack,
	onLevelExplode,
	onSetArmor,
	onFallBlockTransform,
	onUseRespawnAnchorBlock,
	onScoreChanged,
	onMove,
	onPistonPush,
	onEndermanRandomTeleport,
};

const std::unordered_map<std::string, EventCode> events{
{"onConsoleInput",EventCode::onConsoleInput},
{"onConsoleOutput",EventCode::onConsoleOutput},
{"onSelectForm",EventCode::onSelectForm},
{"onUseItem",EventCode::onUseItem},
{"onPlaceBlock",EventCode::onPlaceBlock},
{"onDestroyBlock",EventCode::onDestroyBlock},
{"onOpenChest",EventCode::onOpenChest},
{"onOpenBarrel",EventCode::onOpenBarrel},
{"onCloseChest",EventCode::onCloseChest},
{"onCloseBarrel",EventCode::onCloseBarrel},
{"onContainerChange",EventCode::onContainerChange},
{"onChangeDimension",EventCode::onChangeDimension},
{"onMobDie",EventCode::onMobDie},
{"onMobHurt",EventCode::onMobHurt},
{"onRespawn",EventCode::onRespawn},
{"onChat",EventCode::onChat},
{"onInputText",EventCode::onInputText},
{"onCommandBlockUpdate",EventCode::onCommandBlockUpdate},
{"onInputCommand",EventCode::onInputCommand},
{"onCommandBlockPerform",EventCode::onCommandBlockPerform},
{"onPlayerJoin",EventCode::onPlayerJoin},
{"onPlayerLeft",EventCode::onPlayerLeft},
{"onPlayerAttack",EventCode::onPlayerAttack},
{"onLevelExplode",EventCode::onLevelExplode},
{"onSetArmor",EventCode::onSetArmor},
{"onFallBlockTransform",EventCode::onFallBlockTransform},
{"onUseRespawnAnchorBlock",EventCode::onUseRespawnAnchorBlock},
{"onScoreChanged",EventCode::onScoreChanged},
{"onMove",EventCode::onMove},
{"onPistonPush",EventCode::onPistonPush},
{"onEndermanRandomTeleport",EventCode::onEndermanRandomTeleport},
};
