#pragma once
#include <EventAPI.h>

enum class EventCode {
	onConsoleInput,
	onConsoleOutput,
	onUseItem,
	onPlaceBlock,
	onDestroyBlock,
	onOpenChest,
	onOpenBarrel,
	onCloseChest,
	onCloseBarrel,
	onContainerChange,
	onChangeDimension,
	onMobDie,
	onMobHurt,
	onRespawn,
	onChat,
	onInputText,
	onCommandBlockUpdate,
	onInputCommand,
	onCommandBlockPerform,
	onPlayerJoin,
	onPlayerLeft,
	onPlayerAttack,
	onLevelExplode,
	onSetArmor,
	onFallBlockTransform,
	onUseRespawnAnchorBlock,
	onScoreChanged,
	onMove,
	onPistonPush,
	onEndermanRandomTeleport,
	onServerStarted,
	onDropItem,
	onTakeItem,
	onRide,
	onUseFrameBlock,
	onJump,
	onSneak,
	onBlockInteracted,
	onFireSpread,
	onBlockExploded,
	onUseSignBlock,
};

std::optional<EventCode> StringToEventCode(const std::string& s);

void EnableEventListener(EventCode e);