#pragma once
enum class EventCode {
	/* Player Events */
	onPreJoin,
	onJoin,
	onLeft,
	onRespawn,
	onPlayerDie,
	onPlayerCmd,
	onChat,
	onChangeDim,
	onJump,
	onSneak,
	onAttackEntity,
	onAttackBlock,
	onUseItem,
	onUseItemOn,
	onTakeItem,
	onDropItem,
	onEat,
	onConsumeTotem,
	onEffectChanged,
	onStartDestroyBlock,
	onDestroyBlock,
	onPlaceBlock,
	onOpenContainer,
	onCloseContainer,
	onInventoryChange,
	onMove,
	onChangeSprinting,
	onSetArmor,
	onUseRespawnAnchor,
	onOpenContainerScreen,
	/* Entity Events */
	onMobDie,
	onMobHurt,
	onEntityExplode,
	onProjectileHitEntity,
	onWitherBossDestroy,
	onRide,
	onStepOnPressurePlate,
	onSpawnProjectile,
	onProjectileCreated,
	onNpcCmd,
	onChangeArmorStand,
	onEntityTransformation,
	/* Block Events */
	onBlockInteracted,
	onBlockChanged,
	onBlockExplode,
	onBlockExploded,
	onFireSpread,
	onCmdBlockExecute,
	onContainerChange,
	onProjectileHitBlock,
	onRedStoneUpdate,
	onHopperSearchItem,
	onHopperPushOut,
	onPistonTryPush,
	onPistonPush,
	onFarmLandDecay,
	onUseFrameBlock,
	onLiquidFlow,
	/* Other Events */
	onScoreChanged,
	onTick,
	onServerStarted,
	onConsoleCmd,
	onConsoleOutput,
	/* Economic Events */
	onMoneyAdd,
	onMoneyReduce,
	onMoneyTrans,
	onMoneySet,
	beforeMoneyAdd,
	beforeMoneyReduce,
	beforeMoneyTrans,
	beforeMoneySet,
	/* Outdated Events */
	onMobSpawn,
};
void EnableEventListener(EventCode eventId);
